"""
HMRC MTD ITSA conformance suite — one-command runner.

Produces the transcript file HMRC ask for as part of the SDST recognition
application. The transcript is what proves our wire shapes are accepted
by the live sandbox; the unit-test pytest run proves the contracts are
*pinned* in code, but HMRC want to see them executing against
``test-api.service.hmrc.gov.uk`` too.

What the script does:

  Phase 1 — local unit suite
      Runs every test under ``tests/hmrc/`` with verbose output. These
      cover the wire contracts via mocked HMRC. A pass here proves
      none of the URL/header/body shapes have drifted in code.

  Phase 2 — real-sandbox app-restricted calls
      Runs ``tests/e2e/test_hmrc_real_sandbox.py`` with HMRC_REAL_SANDBOX_E2E=1.
      Exercises the three highest-failure-risk shapes (token,
      create-test-user, create-test-business) against the actual sandbox.

  Phase 3 — real-sandbox user-restricted calls (optional, gated)
      If PROD_TEST_USER_EMAIL/PASSWORD + PROD_SMOKE_FULL=1 are set, runs
      the prod smoke tier 3 which drives the full OAuth dance against
      HMRC's external GG sandbox and hits every user-restricted
      endpoint (obligations, sandbox setup-complete, quarterly preview).

All three phases tee output to ``hmrc/docs/conformance-test-transcript.txt``
prefixed with a header carrying the git SHA + commit date + timestamp so
HMRC reviewers can match the transcript to a specific deploy.

Usage:

    # Phase 1 only (fast, no creds needed):
    python3 scripts/run_conformance_suite.py --phase 1

    # Phases 1 + 2 (needs HMRC sandbox creds):
    HMRC_CLIENT_ID=... HMRC_CLIENT_SECRET=... \\
      python3 scripts/run_conformance_suite.py --phase 2

    # Phases 1 + 2 + 3 (also needs a prod test account):
    HMRC_CLIENT_ID=... HMRC_CLIENT_SECRET=... \\
    PROD_TEST_USER_EMAIL=... PROD_TEST_USER_PASSWORD=... \\
      python3 scripts/run_conformance_suite.py --phase 3

Exit code 0 = all requested phases passed. Non-zero = surface to user
(do NOT submit recognition application until this is green).
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TRANSCRIPT_PATH = ROOT / "hmrc" / "docs" / "conformance-test-transcript.txt"


def _git(args: list[str]) -> str:
    try:
        return subprocess.check_output(
            ["git"] + args, cwd=ROOT, text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        return "<unknown>"


def _write_header(f) -> None:
    f.write("BankScan AI — HMRC MTD ITSA conformance test transcript\n")
    f.write("=" * 60 + "\n")
    f.write(f"Generated:        {datetime.now(timezone.utc).isoformat()}\n")
    f.write(f"Git commit:       {_git(['rev-parse', 'HEAD'])}\n")
    f.write(f"Git branch:       {_git(['rev-parse', '--abbrev-ref', 'HEAD'])}\n")
    f.write(f"Git tag/desc:     {_git(['describe', '--always', '--dirty'])}\n")
    f.write("\n")
    f.write("This file is generated by scripts/run_conformance_suite.py and\n")
    f.write("attached verbatim to the HMRC SDST recognition application.\n")
    f.write("\n")
    f.write("-" * 60 + "\n\n")


def _run_subprocess(cmd: list[str], env: dict, f, label: str) -> int:
    """Run a subprocess, tee its output to both stdout and f."""
    f.write(f"\n{'=' * 60}\n")
    f.write(f"## {label}\n")
    f.write(f"Command: {' '.join(cmd)}\n")
    f.write(f"Started: {datetime.now(timezone.utc).isoformat()}\n")
    f.write(f"{'=' * 60}\n\n")
    f.flush()

    proc = subprocess.Popen(
        cmd, cwd=ROOT, env=env, stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT, text=True, bufsize=1,
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        sys.stdout.write(line)
        sys.stdout.flush()
        f.write(line)
        f.flush()
    rc = proc.wait()
    f.write(f"\nExit: {rc}\nFinished: {datetime.now(timezone.utc).isoformat()}\n\n")
    return rc


def _phase_1_local_unit(env: dict, f) -> int:
    """Mocked HMRC unit tests — pins every wire contract."""
    return _run_subprocess(
        [sys.executable, "-m", "pytest", "tests/hmrc/", "-v", "--tb=short", "--no-header"],
        env, f, "Phase 1 — Local unit tests (mocked HMRC)",
    )


def _phase_2_real_sandbox_app_restricted(env: dict, f) -> int:
    """Hits the real sandbox with an application-restricted token."""
    if not (env.get("HMRC_CLIENT_ID") and env.get("HMRC_CLIENT_SECRET")):
        f.write("\n## Phase 2 SKIPPED — HMRC_CLIENT_ID / HMRC_CLIENT_SECRET not set.\n")
        f.write("Submit the .env.hmrc values before running this phase.\n")
        return 99
    env_with_gate = {**env, "HMRC_REAL_SANDBOX_E2E": "1"}
    return _run_subprocess(
        [sys.executable, "-m", "pytest", "tests/e2e/test_hmrc_real_sandbox.py",
         "-v", "--tb=short", "--no-header", "-m", "hmrc_sandbox"],
        env_with_gate, f,
        "Phase 2 — Real sandbox (app-restricted: token, test-user, test-business)",
    )


def _phase_3_real_sandbox_user_restricted(env: dict, f) -> int:
    """Drives Playwright through full GG OAuth + hits user-restricted endpoints."""
    needed = ["PROD_TEST_USER_EMAIL", "PROD_TEST_USER_PASSWORD"]
    missing = [k for k in needed if not env.get(k)]
    if missing:
        f.write(f"\n## Phase 3 SKIPPED — missing {', '.join(missing)}.\n")
        f.write("These drive the full OAuth handshake against HMRC's GG sandbox.\n")
        return 99
    env_with_gates = {
        **env,
        "PROD_SMOKE": "1",
        "PROD_SMOKE_FULL": "1",
    }
    return _run_subprocess(
        [sys.executable, "-m", "pytest",
         "tests/e2e/test_prod_hmrc_smoke.py",
         "--browser", "chromium",
         "-v", "--tb=short", "--no-header"],
        env_with_gates, f,
        "Phase 3 — Real sandbox (user-restricted: OAuth + obligations + quarterly preview)",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--phase", type=int, default=1, choices=[1, 2, 3],
        help="Highest phase to run (each phase implies all earlier ones).",
    )
    parser.add_argument(
        "--output", default=str(TRANSCRIPT_PATH),
        help="Where to write the transcript (default: hmrc/docs/conformance-test-transcript.txt)",
    )
    args = parser.parse_args()

    env = os.environ.copy()
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"Writing conformance transcript to {out_path}")
    rc_total = 0
    with out_path.open("w") as f:
        _write_header(f)

        rc_total |= _phase_1_local_unit(env, f)

        if args.phase >= 2:
            rc2 = _phase_2_real_sandbox_app_restricted(env, f)
            if rc2 not in (0, 99):
                rc_total |= rc2

        if args.phase >= 3:
            rc3 = _phase_3_real_sandbox_user_restricted(env, f)
            if rc3 not in (0, 99):
                rc_total |= rc3

        f.write("\n" + "=" * 60 + "\n")
        f.write(f"## Final result: {'PASS' if rc_total == 0 else 'FAIL'}\n")
        f.write("=" * 60 + "\n")

    if rc_total == 0:
        print("\nPASS — transcript ready for HMRC recognition application.")
        print(f"Attach: {out_path}")
    else:
        print("\nFAIL — DO NOT submit recognition application yet. See transcript.")
    return rc_total


if __name__ == "__main__":
    sys.exit(main())
